import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import nodemailer from 'nodemailer';

export async function POST(request: Request) {
  try {
    const data = await request.json();
    const { name, company, role, postcode, email, phone, message } = data;

    if (!name || !email || !message) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const enquiry = await prisma.contactEnquiry.create({
      data: {
        name,
        company,
        role,
        postcode,
        email,
        phone,
        message,
      },
    });

    try {
      const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: process.env.GMAIL_USER,
          pass: process.env.GMAIL_APP_PASSWORD,
        },
      });

      const logoPath = require('path').join(process.cwd(), 'public', 'assets', 'logo.png');

      transporter.sendMail({
        from: process.env.GMAIL_USER,
        to: process.env.RECEIVER_EMAIL,
        subject: `New Enquiry Submitted from ${name}`,
        html: `
        <!DOCTYPE html>
        <html>
        <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f4f7f6; margin: 0; padding: 0; }
          .container { max-width: 600px; margin: 20px auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
          .header { background-color: #1a202c; padding: 30px; text-align: center; }
          .header img { max-height: 80px; width: auto; }
          .content { padding: 30px; color: #2d3748; line-height: 1.6; }
          .content h2 { margin-top: 0; color: #1a202c; border-bottom: 2px solid #edf2f7; padding-bottom: 15px; margin-bottom: 25px; }
          .field { margin-bottom: 20px; }
          .label { font-weight: bold; color: #4a5568; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
          .value { display: block; margin-top: 5px; font-size: 16px; background: #f7fafc; padding: 12px; border-radius: 4px; border: 1px solid #e2e8f0; }
          .message-box { display: block; margin-top: 5px; background: #f7fafc; padding: 15px; border-radius: 4px; border: 1px solid #e2e8f0; font-size: 15px; white-space: pre-wrap; }
          .footer { background: #edf2f7; padding: 20px; text-align: center; font-size: 13px; color: #718096; }
          @media only screen and (max-width: 600px) {
            .container { margin: 0; border-radius: 0; width: 100%; }
          }
        </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <img src="cid:logo" alt="Foil Quilt Logo" />
            </div>
            <div class="content">
              <h2>New Enquiry Submitted</h2>
              <p style="margin-bottom: 25px;">A new enquiry has been submitted through your website.</p>
              
              <div class="field">
                <span class="label">Name</span>
                <span class="value">${name}</span>
              </div>
              <div class="field">
                <span class="label">Email</span>
                <span class="value">${email}</span>
              </div>
              <div class="field">
                <span class="label">Phone</span>
                <span class="value">${phone || 'Not provided'}</span>
              </div>
              <div class="field">
                <span class="label">Company</span>
                <span class="value">${company || 'Not provided'}</span>
              </div>
              <div class="field">
                <span class="label">Role</span>
                <span class="value">${role || 'Not provided'}</span>
              </div>
              <div class="field">
                <span class="label">Postcode</span>
                <span class="value">${postcode || 'Not provided'}</span>
              </div>
              <div class="field">
                <span class="label">Message</span>
                <span class="message-box">${message}</span>
              </div>
            </div>
            <div class="footer">
              This email was automatically generated by your website's contact form.
            </div>
          </div>
        </body>
        </html>
        `,
        attachments: [
          {
            filename: 'logo.png',
            path: logoPath,
            cid: 'logo' // same cid value as in the html img src
          }
        ]
      }).catch(emailError => {
        console.error('Error sending email:', emailError);
      });
    } catch (setupError) {
      console.error('Error setting up email:', setupError);
    }

    return NextResponse.json({ success: true, enquiry }, { status: 201 });
  } catch (error) {
    console.error('Error saving contact enquiry:', error);
    return NextResponse.json(
      { error: 'Failed to save enquiry' },
      { status: 500 }
    );
  }
}
